# Generated by Django 3.2.5 on 2022-04-28 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swastikapp', '0002_auto_20220427_1735'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShippingAddress',
        ),
    ]
