# Generated by Django 4.0.4 on 2022-04-29 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swastikapp', '0004_doctors'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='hospital_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='doctors',
            name='specialist',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='image',
            field=models.ImageField(null=True, upload_to='Doctor'),
        ),
    ]
